[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# This single rule sends all requests that don't match a file
# in the 'publish' directory to your serverless function.
# The Express server inside the function will then handle all routing.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200